---
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install httpd
      yum: name=httpd state=present
      async: 300
      poll: 3
      notify:
      -  Restart HTTPD
  handlers:
    - name: Restart HTTPD
      service: name=httpd state=restarted


